#!/bin/sh

HOME=/home/odroid
RKNN=/home/odroid/rknpu2/runtime/RK356X/Linux/librknn_api/aarch64/librknnrt.so
WHL=${HOME}/rknn-toolkit2/rknn_toolkit_lite2/packages/rknn_toolkit_lite2-1.5.2-cp38-cp38-linux_aarch64.whl

python3 -m venv ${HOME}/.rknn

echo "========== git clone start =========="
git clone https://github.com/hardkernel/rknpu2 ${HOME}/rknpu2
git clone https://github.com/hardkernel/rknn-toolkit2 ${HOME}/rknn-toolkit2
echo "========== git clone finish =========="

echo "========== pip install start =========="
[ -f ${WHL} ] && yes | ${HOME}/.rknn/bin/python3 -m pip install ${WHL}
yes | ${HOME}/.rknn/bin/python3 -m pip install opencv-python
echo "========== pip install finish =========="

echo "========== examples seting start =========="
chown -R odroid:odroid ${HOME}/rknpu2/
chown -R odroid:odroid ${HOME}/rknn-toolkit2/
chown -R odroid:odroid ${HOME}/.rknn/
[ -f ${RKNN} ] && ln -s ${RKNN} /usr/lib/librknnrt.so
echo "========== examples seting finish =========="

echo "# activate venv at first"
echo "source ${HOME}/.rknn/bin/activate" >> ${HOME}/.bashrc
echo "export LD_LIBRARY_PATH=${HOME}/rknpu2/examples/rknn*/install/*/lib" >> ${HOME}/.bashrc
