#!/bin/sh

echo "=== install ros-base ==="

DEFAULT_DISTRO=@@DEFAULT_DISTRO@@

apt update

case ${DEFAULT_DISTRO} in
  focal)
    apt install @@DEFAULT_APT_OPTIONS@@ \
    ros-foxy-ros-base
    ;;
  jammy)
    apt install @@DEFAULT_APT_OPTIONS@@ \
    ros-humble-ros-base
    ;;
esac
