#!/bin/sh

export DEBIAN_FRONTEND=noninteractive

rm -f /etc/apt/sources.list.d/launchpad-hardkernel-ppa.list

apt-key adv --keyserver keyserver.ubuntu.com \
	--recv-keys 4F71126C02B8F823

apt update --allow-releaseinfo-change \
	&& apt upgrade -y
apt install @@DEFAULT_APT_OPTIONS@@ \
	odroid-base \
	rsync \
	@@DEFAULT_FLAVOUR_PACKAGES@@ \
	@@DEFAULT_KERNEL_PACKAGE@@ \
	@@DEFAULT_BOOTSCRIPT_PACKAGE@@ || exit 1

if ls /overlay/host/debs/*.deb 1>/dev/null 2>&1; then
	dpkg -i $(ls /overlay/host/debs/*.deb)
	apt install --fix-broken @@DEFAULT_APT_OPTIONS@@
fi

DKMS=$(dpkg -l | grep dkms | awk '{print $2}')
if [ "x$DKMS" != "x" ]; then
	LINUX_HEADER=$(dpkg -l | grep linux-image-[0-9].* | awk '{print $2}' | sed "s/image/headers/g")
	apt install @@DEFAULT_APT_OPTIONS@@ $LINUX_HEADER

	for dkms in $DKMS; do
		dpkg-reconfigure $dkms
	done
fi

apt remove -y @@DEFAULT_BLACKLIST_PACKAGES@@
